[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "datacite-metadata-schema"
authors = [{name = "DataCite Metadata Working Group", email = "support@datacite.org"}]
dynamic = ["version", "description"]
