[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
name = "datacite-metadata-schema"
author = "DataCite Metadata Working Group"
author-email = "support@datacite.org"
